services:
  presales-crew:
    build: .
    container_name: presales-crew
    volumes:
      - ./presales_crew:/app/presales_crew
      - ./knowledge:/app/knowledge
      - ./presales_crew/outputs:/app/presales_crew/outputs
  presales-crew-tests:
    build: .
    container_name: presales-crew-tests
    volumes:
      - ./presales_crew:/app/presales_crew
      - ./knowledge:/app/knowledge
      - ./presales_crew/outputs:/app/presales_crew/outputs
    working_dir: /app
    environment:
      - PYTHONPATH=/app/presales_crew/src
      
    command: ["pytest", "presales_crew/tests"] 