services:
  presales-app:
    build: .
    container_name: presales-app
    volumes:
      - ./presales_crew:/app/presales_crew
    working_dir: /app/presales_crew/src
    environment:
      - PYTHONPATH=/app/presales_crew/src
    command: ["python", "-m", "presales_crew.main"]
  presales-test:
    build: .
    container_name: presales-test
    volumes:
      - ./presales_crew:/app/presales_crew
    working_dir: /app
    environment:
      - PYTHONPATH=/app/presales_crew/src
    command: ["pytest", "presales_crew/tests"] 