name: Docker Build

on:
  push:
    branches:
      - '**'

jobs:
  build_docker_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with Compose
        run: |
          docker compose build --progress=plain

      - name: Log Docker images
        run: |
          docker images